menu_items = [
    {
        "id": 1,
        "tenant_id": 1,
        "branch_id": 1,
        "category_id": 1,
        "name": "Masala Poha",
        "description": "Fresh poha with peanuts and sev",
        "price": 45,
        "is_veg": True,
        "is_available": True,
        "preparation_time": 8,
        "image": "",
        "is_active": True
    },
    {
        "id": 2,
        "tenant_id": 1,
        "branch_id": 1,
        "category_id": 2,
        "name": "Cold Coffee",
        "description": "Creamy chilled coffee",
        "price": 60,
        "is_veg": True,
        "is_available": True,
        "preparation_time": 10,
        "image": "",
        "is_active": True
    },
    {
        "id": 3,
        "tenant_id": 1,
        "branch_id": 2,
        "category_id": 3,
        "name": "Executive Thali",
        "description": "Daily office lunch combo",
        "price": 120,
        "is_veg": True,
        "is_available": True,
        "preparation_time": 15,
        "image": "",
        "is_active": True
    },
    {
        "id": 4,
        "tenant_id": 1,
        "branch_id": 2,
        "category_id": 4,
        "name": "Paneer Puff",
        "description": "Flaky bakery puff with paneer filling",
        "price": 35,
        "is_veg": True,
        "is_available": True,
        "preparation_time": 6,
        "image": "",
        "is_active": True
    },
    {
        "id": 5,
        "tenant_id": 1,
        "branch_id": 3,
        "category_id": 5,
        "name": "Mini Idli Sambar",
        "description": "Soft idlis with hot sambar",
        "price": 70,
        "is_veg": True,
        "is_available": True,
        "preparation_time": 12,
        "image": "",
        "is_active": True
    },
    {
        "id": 6,
        "tenant_id": 1,
        "branch_id": 3,
        "category_id": 6,
        "name": "Fresh Lime Soda",
        "description": "Sweet and salted lime soda",
        "price": 40,
        "is_veg": True,
        "is_available": True,
        "preparation_time": 4,
        "image": "",
        "is_active": True
    }
]
